plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/macbook/Desktop/site /DMT-autogroup"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/services/garage-automobile.html"
to = "/garage-automobile.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/pneus.html"
to = "/pneus.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/carrosserie.html"
to = "/carrosserie.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/mecanique-automobile.html"
to = "/mecanique-automobile.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/vidange-huile.html"
to = "/vidange-huile.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/controle-technique.html"
to = "/controle-technique.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services/boite-dsg.html"
to = "/boite-dsg.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]